steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'app'
      - 'deploy'
      - './app.yaml'  # Specify the path to app.yaml relative to cloudbuild.yaml
    env:
      - 'CLOUDSDK_CORE_DISABLE_PROMPTS=1'

timeout: '1200s'
